### ISSUE TITLE
Supprimer les doublons 

### ISSUE THREAD

**Issue by alexislozano** [alexislozano/salaires.dev#1]
Le bouton d'envoi a 4 states:
- Init
- Loading
- Success
- Error

Il ne devrait être activé que si son state est Init.

De plus, le formulaire devrait être réinitialisé lors d'un envoi se terminant sur un succès.

**Comment by Chcap** [comment]
Je suggère également que suite à l'envoi, en plus de la réinitialisation du formulaire de:
- scroller en haut du formulaire
- afficher un message en bandeau indiquant que l'envoi a bien été effectué

**Comment by alexislozano** [comment]
J'ai fait les changements dans https://github.com/alexislozano/salaires.dev/commit/5333f5c25105adc3416de5c0b4cd32f4c2e1d5fb.

Au final, le bouton d'envoi a deux states :
- Init -> activé
- Loading -> désactivé

Une notification apparaît pour montrer que l'envoi a été effectué ou qu'il y a eu une erreur.
