### ISSUE TITLE
Gestion des erreurs 

### ISSUE THREAD

**Issue by alexislozano** [alexislozano/salaires.dev#10]
Pour l'instant on a pas mal de 500 avec un message texte. À changer en status code plus précis. Et affichage des erreurs côté front.

**Comment by petitkriket** [comment]
Hello,

Retour de bug, le front ne réagit pas au 200 success et n'affiche pas les données en 200

<img width="1436" alt="Capture d’écran 2022-08-22 à 12 49 54" src="https://user-images.githubusercontent.com/1753019/185904201-8c532624-91e7-45dc-bb5f-f15177f68a22.png">

**Comment by alexislozano** [comment]
Résolu dans :
https://github.com/alexislozano/salaires.dev/commit/055e815761d47d8ea2a8037bad061361a4962ef6

**Comment by alexislozano** [comment]
Avec le passage à Rust only, j'ai géré toutes les erreurs à base de notifs
