### ISSUE TITLE
Ajout de docs

### ISSUE THREAD

**Issue by RaboliotLeGris** [alexislozano/salaires.dev#14]
Salutations!

Je viens d'essayer de faire tourner l'app sans grand succès. Il semble qu'il manque un bon morceau de docs sur la configs de dev.

J'ai pu deviner l'utilisation de Supabase, les différentes variables d'environnement mais je crois qu'il me manque quelques trucs.

**Comment by alexislozano** [comment]
Salut ! J'ai ajouté des fichiers `.env.example` dans https://github.com/alexislozano/salaires.dev/commit/a79347349aa6a954010c072472390c57e0f10729. J'espère que ça va t'aider :slightly_smiling_face:

**Comment by RaboliotLeGris** [comment]
En partie, merci !

Ce qui serait sympa aussi, ce serait les schémas utilisés sur Supabase, ça pourrait éviter de devoir tous les créer à la main.

**Comment by alexislozano** [comment]
J'ai rajouté les commandes supabase à faire dans la doc dans https://github.com/alexislozano/salaires.dev/commit/de59dbcb2d13c65f0780fef4d7fd7cf5c2e20483. Dis-moi si tu penses qu'il manque encore quelque chose :pray:

**Comment by RaboliotLeGris** [comment]
Je pense que ça devrait déjà bien aider, je ferme l'issue :)
