### ISSUE TITLE
RGPD

### ISSUE THREAD

**Issue by alexislozano** [alexislozano/salaires.dev#17]
Se documenter et voir quelles actions sont à faire.

**Comment by Grandasse** [comment]
Vous récoltez les emails pro avec des noms dedans, du coup vous stockez des données personnelles.
Il faut donc : 
- informer les utilisateurs du type de données collectées, leurs durée de conservation, etc (Art. 13)

Soit vous décidez de ne pas stocker les mails, soit vous devez : 
- mettre à disposition un email pour que les personnes puisse faire valoir leurs droits (Art. 15 à 20)

https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=celex%3A32016R0679

et on croise les doigts pour qu'il n'y ait jamais de leak de la BDD

**Comment by alexislozano** [comment]
@Grandasse Merci pour les infos, je gère ça ce weekend 🙏

> et on croise les doigts pour qu'il n'y ait jamais de leak de la BDD

Les adresses emails sont supprimées dès la publication du salaire, donc au maximum l'attaquant ne récupérerait que celles qui ne sont pas encore publiées (les plus récentes parce que je publie dans la journée de réception max).

**Comment by alexislozano** [comment]
@Grandasse J'ai fait les modifs:

- j'ai ajouté [une page RGPD](https://salaires.dev/rgpd) avec un lien dans le header du site et sur [le formulaire d'ajout](https://salaires.dev/insert).
- j'ai modifié le code pour que le site n'affiche aucun salaire si un salaire est publié et a encore l'adresse email définie
- j'ai ajouté un cron pour me prévenir quand un salaire ajouté est expiré (non publié 7 jours après son ajout)

Si c'est bon pour toi je te laisse fermer l'issue.

**Comment by Grandasse** [comment]
Sound good! 

(je pense pas avoir les droits pour fermer l'issue par contre)

**Comment by alexislozano** [comment]
@Grandasse Ah oui bien sûr :sweat_smile: Je ferme moi-même alors, merci encore pour les liens.
