### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by Ezibenroc** [alexislozano/salaires.dev#23]
Hello,

Would it be possible to provide a CSV dump of the database somewhere? This would allow other persons to play a bit with this data (some statistics, visualizations, etc).

In the short term, you could manually dump it and upload it somewhere (e.g. as an artifact of a github release). A better solution would be to automatize this and update the CSV regularly, e.g. every day or every week.

------

Some libraries (like pandas) offer basic [web-scrapping functionalities](https://pythonbasics.org/pandas-web-scraping/) for tables. For instance:
```python
import pandas as pd

url = 'https://en.wikipedia.org/wiki/History_of_Python'
dfs = pd.read_html(url)

print(len(dfs))
```

But this does not work with https://salaires.dev/ (I guess because the content of the table is loaded with JS).
So at the moment, the only alternative is a big `Ctrl-A Ctrl-C Ctrl-V`, which is far from ideal 😞

**Comment by alexislozano** [comment]
@Ezibenroc Hello ! You should be able to fetch the data in json via the api:

https://api.salaires.dev/salaries

Would it work for you?

**Comment by Ezibenroc** [comment]
Awesome, thank you!
