### ISSUE TITLE
Stocks - une description plus précise 

### ISSUE THREAD

**Issue by Shaance** [alexislozano/salaires.dev#24]
On reçoit généralement des stocks sur une période de 4 ans. Ce n'est pas clair si l'on doit renseigner cette somme totale ou la somme par an (d'où la disparité des chiffres qu'on peut observer sur la partie stocks)

**Comment by alexislozano** [comment]
@Shaance J'ai pour projet d'enlever la colonne en fait :slightly_smiling_face:

**Comment by Shaance** [comment]
Pourquoi ça? C'est une partie très important de la rémunération pour certains

**Comment by alexislozano** [comment]
@Shaance J'ai supprimé la colonne :smile:
