### ISSUE TITLE
"Niveau" ça veut dire quoi ?

### ISSUE THREAD

**Issue by foucdeg** [alexislozano/salaires.dev#25]
Je n'ai pas compris cette colonne en remplissant mon salaire.

Certains l'ont visiblement prius comme un niveau d'études, d'autres comme un niveau de poste.

**Comment by theo-dep** [comment]
Je viens de m'en rendre compte. J'ai repli comme niveau dans la grille salariale de la convention...

**Comment by alexislozano** [comment]
@foucdeg @theo-dep Ça fait plusieurs fois qu'on me fait la remarque. Initialement je pensais aux niveaux genre L1, L2... qu'il y a chez les GAFAM et assimilés. Mais c'est pas comparable entre les boîtes et ça perd pas mal de monde.

Donc je suis passé aux basiques "Junior", "Intermédiaire", et "Senior" dans [ce commit](029c42d0d2dbb93c7b06f1db12ec5ea58db8b743).

Résultat sur le site:

![Capture d’écran du 2023-02-14 23-22-15](https://user-images.githubusercontent.com/50751082/218876823-351a96d9-9cfb-4797-a6a6-284a0410ebdd.png)
