### ISSUE TITLE
Typo in email

### ISSUE THREAD

**Issue by theo-dep** [alexislozano/salaires.dev#26]
"Confirmez votre salaire**s** en cliquant sur ce lien:"
![image](https://user-images.githubusercontent.com/43611658/218260346-e18276bb-a769-4bd9-84df-4df6be2879d2.png)

**Comment by alexislozano** [comment]
@theo-dep Merci, c'est résolu [ici](486b0d4a1fea8db6289be1759dcbc8ae56081ed8)
