### ISSUE TITLE
Expériences - Tri descendant ressort les entrées vide en premier

### ISSUE THREAD

**Issue by Totara-thib** [alexislozano/salaires.dev#27]
## Context

Lorsqu'on effectue un tri de manière descendante sur `Expérience entreprise` et `Expérience totale` les entrées vides se retrouve dans les premiers résultats

![image](https://user-images.githubusercontent.com/78480448/224073706-7b00ca7c-86fc-442e-9779-a6ca552d1274.png)

## Attendu

Que les entrées vides se retrouve dans les derniers résultats après 0

**Comment by alexislozano** [comment]
@Totara-thib Hello :wave: Apparemment le sort de supabase classe les null de manière bizarre. Du coup je l'ai gardé et je fais un sort logiciel en plus (d041d94).

Le fix est en prod. Si c'est ok pour toi, je te laisse fermer l'issue :slightly_smiling_face:
