### ISSUE TITLE
Impossible de confirmer le lien de salaire

### ISSUE THREAD

**Issue by ncomet** [alexislozano/salaires.dev#28]
Bonjour, impossible de valider le lien qui arrive dans ma boite mail pro.

**Comment by alexislozano** [comment]
Bonjour @ncomet et merci pour ton issue.

- est ce que tu reçois le lien par email ?
- que se passe-t-il lorsque tu cliques dessus ?

**Comment by ncomet** [comment]
Je le reçois bien, lorsque je clique dessus, j'ai le bandeau de notif "Le salaire n'a pas pu être confirmé" qui s'affiche sur salaires.dev

Mon entreprise met un filtre outlook, mais en copiant et en url décodant ça reste invalide.

Voici le lien invalide que j'url decode:
```
https://salaires.dev/?token=8368517806859482685389955702861782234422008509457347925150775636&data=05|01|nicolas.comet@ubisoft.com|de0182b806cb43f8800208db71951921|e01bd386fa514210a2a429e5ab6f7ab1|0|0|638228657410823494|Unknown|TWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0=|3000|||&sdata=jC7TcVKB8shT/RGT3avvAPqBt1KtJTKz22YCB0gtlQA=&reserved=0
```

**Comment by alexislozano** [comment]
@ncomet Pas de souci :)

**Comment by mamyn0va** [comment]
J'ai le même souci. Je reçois bien le lien qui contient un token, mais quand je clique dessus, ça me met un bandeau "Le salaire n'a pas pu être confirmé".

**Comment by alexislozano** [comment]
Bonjour @mamyn0va. J'ai reçu un seul salaire aujourd'hui, et il a bien été confirmé. Je l'ai publié, tu peux me dire si c'est bien le tien ? Si oui j'imagine que tu as dû cliquer sur le lien deux fois sans le faire exprès.

**Comment by mamyn0va** [comment]
Effectivement !
Merci

---

La planète a besoin de vous !

🌍 [Alternatiba Caen](https://alternatiba.eu/caen/)
🚧 [eXtinction Rebellion](https://extinctionrebellion.fr/)
💪 [SuperLocal](https://superlocal.team/)
✊ [OnEstLa.Tech](https://onestla.tech/)

Envoyé depuis Proton Mail mobile

-------- Message d'origine --------
