### ISSUE TITLE
[Suggestion] Ajout colonne "nombre minimal de journées en présentiel"

### ISSUE THREAD

**Issue by Shrakka** [alexislozano/salaires.dev#30]
Par mois ? Par semaine ? Interessant ou pas ?

**Comment by alexislozano** [comment]
Coucou @Shrakka :wave: On se connaît non ? :stuck_out_tongue_winking_eye: C'est une bonne idée, je pensais ajouter un nouveau champ dans le form:

```
Modalités de télétravail - Optionnel
  o Pas de télétravail
  o Télétravail complet
  o Télétravail partiel
      [2   ] jours par [semaine v] <-- ceci est un dropdown avec deuxième choix = mois
```

Bien sûr les deux inputs (number et select) auront un `aria-label` pour l'accessibilité.

**Comment by Shrakka** [comment]
Mon lama n'est pas passé inaperçu o/ 

Super le champ 👌  Pour le Dropdown, je préciserais l'un ou l'autre pour éviter les mal entendu : 

```
Modalités de télétravail - Optionnel
  o Pas de télétravail
  o Télétravail complet
  o Télétravail partiel
      [2] jours par [semaine] de présence obligatoire
```

OU 

```
Modalités de télétravail - Optionnel
  o Pas de télétravail
  o Télétravail complet
  o Télétravail partiel
      [2] jours par [semaine] de télétravail autorisé(s)
```

Je ne sais pas trop quelle option est la meilleure, la formulation dans le contrat n'est pas toujours la même selon les entreprises :) Celle qui te convient le mieux fera l'affaire :D

**Comment by alexislozano** [comment]
L'info qui doit sauter au yeux pour moi lorsqu'on regarde une offre, c'est le nombre de jours de TT, pas le nb de jours au bureau. Donc je garde la version 2 :slightly_smiling_face:

**Comment by alexislozano** [comment]
@Shrakka Finalement j'ai mis les deux possibilités :

![image](https://github.com/alexislozano/salaires.dev/assets/50751082/70e4197e-c3ed-4990-b210-a6520a4d73fa)

Tu peux essayer sur staging si tu veux: https://staging.salaires.dev/insert

Qu'en penses-tu ?

**Comment by Shrakka** [comment]
C'est parfait en terme d'interface 👌 !

**Comment by alexislozano** [comment]
J'ai ajouté un petit fix sur le focus, et c'est en prod :tada:
