### ISSUE TITLE
Accessibilité Web a11y

### ISSUE THREAD

**Issue by davidaparicio** [alexislozano/salaires.dev#7]
Vérification de la conformité avec les outils de validation, pour l'accessibilité Web: WCAG (Web Content Accessibility Guidelines)

On pourra se baser sur le talk de DevoxxFR 2022: "Mon site déjà en ligne doit être accessible, je fais comment ?" (par Mélanie Boudard) https://youtu.be/9QuNM0CUycM

**Comment by alexislozano** [comment]
On est sur du HTML sémantique. Après test sur lighthouse, l'accessibilité est ok:

![image](https://user-images.githubusercontent.com/50751082/227728819-0a660a0d-df29-4492-bfad-650ae4d68fc5.png)
